### ISSUE TITLE
Polytone Handshake

### ISSUE THREAD

**Issue by 0xekez** [DA0-DA0/polytone#4]
![image](https://user-images.githubusercontent.com/30676292/227067393-49c245e1-e34a-4245-9950-aed06316dbb5.png)

In psudocode:

```
def init():
  version = "polytone" 
  true
```

```
def try():
  if version == "polytone":
    version = ["JSON", ...extensions]
    true
  else:
    false
```

```
def ack():
  if note:
    supported.is_subset(version)
  else:
    version.is_subset(supported)
```

```
def confirm():
  true
```

**Comment by 0xekez** [comment]
complete spec here:

https://gist.github.com/0xekez/ea27a25d9de566a579ade4e436f89ff7

**Comment by Art3miX** [comment]
> another way of saying this is that notes express optional preferences by observing the contents of the voice extensions.

Do we even need "supported features" in the handshake/version? 

If note tries to send an invalid msg to voice, that msg will fail, and it is logical, "if you want to talk with osmosis, you need to know what msgs osmosis have".

Biggest issue seems to be handling the error, obviously best case is to handle it on the note (before sending IBC), and it seems like this is sort of a way to do it.

And if we do want this "supported features" feature, does the note also need to have it? because the note doesn't really care what msgs are gonna be sent over to the other chain, all it cares is to handle those errors before they are sent.
If note support `init2` but voice doesn't, it doesn't make sense to fail the handshake because of it, it just means init2 msgs shouldn't be sent.
